language: ruby
rvm:
- 2.2.0
env:
global:
- RUN_ON_SAUCE: true
addons:
sauce_connect: true
install:
- bundle install
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
script:
- bundle exec rake db:drop db:create db:migrate db:seed
- bundle exec rspec
